#!/usr/bin/env python3
"""
generator.py — Main code generation script for the rvvfft library.

Usage:
    python generator.py [options]

Options:
    --radix    RADIX [RADIX ...]   Radix values to generate (default: 2 4 8)
    --dtype    DTYPE [DTYPE ...]   Data types: f32, f64 (default: f32 f64)
    --vlen     VLEN  [VLEN ...]    Vector lengths: 256, 1024 (default: 256 1024)
    --lmul     LMUL  [LMUL ...]    LMUL values: 1 2 4 8 (default: auto)
    --layout   LAYOUT [LAYOUT ...] Layouts: interleaved, split (default: both)
    --outdir   DIR                 Output directory (default: ../src/kernel/generated)
    --verify                       Run verify_math.py before generation
    --registry FILE                Write codelet_registry.h to FILE
    --dry-run                      Print file names without writing

The generator:
  1. Builds a DFT DAG for each (radix, group=0) combination.
  2. Applies the symbolic simplifier to eliminate trivial twiddle multiplies.
  3. Renders the butterfly.c.j2 Jinja2 template for each parameter combination.
  4. Writes generated .c files to the output directory.
  5. Writes a codelet_registry.h enumerating all generated kernels.

Mathematical correctness of each generated kernel is guaranteed by:
  - DAG construction in dag.py (mathematically-principled butterfly algorithms)
  - Symbolic simplification rules verified by verify_math.py (SymPy)
  - Runtime bit-exact comparison against handwritten reference in CI
"""

from __future__ import annotations
import argparse
import datetime
import math
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

# ── Optional dependencies ──────────────────────────────────────────────────

try:
    from jinja2 import Environment, FileSystemLoader
    _JINJA2_OK = True
except ImportError:
    _JINJA2_OK = False
    print("[generator] WARNING: Jinja2 not found.  Install it with: "
          "pip install jinja2\n"
          "  Template rendering will be skipped; only the registry will be written.")

# Codegen modules
_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE))

from dag import (
    DFT_DAG, build_radix2_butterfly, build_radix4_butterfly,
    build_radix8_butterfly
)
from simplify import simplify_dag

GENERATOR_VERSION = "0.1.0"

# ──────────────────────────────────────────────────────────────────────────────
# Configuration dataclass
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class KernelConfig:
    """All parameters describing one generated butterfly kernel."""
    radix:   int
    dtype:   str    # 'f32' | 'f64'
    vlen:    int    # 256 | 1024
    lmul:    int    # 1 | 2 | 4 | 8
    layout:  str    # 'interleaved' | 'split'

    @property
    def sew(self) -> int:
        return 32 if self.dtype == 'f32' else 64

    @property
    def vl_max(self) -> int:
        """Maximum number of scalar elements per vector register group."""
        return (self.vlen * self.lmul) // self.sew

    @property
    def func_name(self) -> str:
        return (f"rvvfft_butterfly_r{self.radix}_{self.dtype}"
                f"_vlen{self.vlen}_m{self.lmul}_{self.layout[:5]}")

    @property
    def file_name(self) -> str:
        return self.func_name + ".c"

    def is_valid(self) -> bool:
        """Check that LMUL does not overflow the register file (32 regs)."""
        regs_needed = self.radix * 2 * self.lmul  # r+i per input × LMUL groups
        return regs_needed <= 32


# ──────────────────────────────────────────────────────────────────────────────
# Auto-select LMUL
# ──────────────────────────────────────────────────────────────────────────────

def best_lmul(radix: int, vlen: int, sew: int) -> int:
    """
    Choose the largest LMUL that keeps register pressure within 32 vector regs.

    Heuristic:
      - Each butterfly needs radix × 2 (real+imag) input + output vectors.
      - With LMUL=m, each logical register uses m physical registers.
      - Constraint: radix * 2 * LMUL * 2  ≤ 32   (inputs + temps + outputs)
    """
    for lmul in [8, 4, 2, 1]:
        cfg = KernelConfig(radix=radix, dtype='f32', vlen=vlen,
                           lmul=lmul, layout='split')
        if cfg.is_valid():
            return lmul
    return 1


# ──────────────────────────────────────────────────────────────────────────────
# Registry header
# ──────────────────────────────────────────────────────────────────────────────

REGISTRY_HEADER_TMPL = """\
/**
 * codelet_registry.h — AUTO-GENERATED by rvvfft codegen {version}
 * Generated: {timestamp}
 *
 * Lists all butterfly kernel functions produced by generator.py.
 * Include this file to get forward declarations for all kernels.
 * DO NOT EDIT — re-run generator.py to regenerate.
 */

#ifndef RVVFFT_CODELET_REGISTRY_H
#define RVVFFT_CODELET_REGISTRY_H

#include <stddef.h>
#include "rvvfft_types.h"

#ifdef __cplusplus
extern "C" {{
#endif

/* ── Interleaved layout ─────────────────────────────────────────────── */
{interleaved_decls}

/* ── Split layout ───────────────────────────────────────────────────── */
{split_decls}

/* ── Codelet descriptor ─────────────────────────────────────────────── */
typedef void (*rvvfft_codelet_fn)(const float *, float *, size_t,
                                   const float *, const float *);

typedef struct {{
    int            radix;
    const char    *dtype;      /* "f32" or "f64" */
    int            vlen;       /* 256 or 1024    */
    int            lmul;       /* 1,2,4,8        */
    const char    *layout;     /* "interleaved" or "split" */
    rvvfft_codelet_fn fn;
}} rvvfft_codelet_entry_t;

/* Global table of all registered codelets (NULL-terminated) */
extern const rvvfft_codelet_entry_t rvvfft_codelet_table[];

#ifdef __cplusplus
}}
#endif

#endif /* RVVFFT_CODELET_REGISTRY_H */
"""

DECL_TMPL_INTERLEAVED = (
    "void {func_name}(const {scalar_t} * __restrict__ in,\n"
    "                 {scalar_t} * __restrict__ out,\n"
    "                 size_t n,\n"
    "                 const {scalar_t} * __restrict__ tw_r,\n"
    "                 const {scalar_t} * __restrict__ tw_i);"
)

DECL_TMPL_SPLIT = (
    "void {func_name}(const {scalar_t} * __restrict__ in_r,\n"
    "                 const {scalar_t} * __restrict__ in_i,\n"
    "                 {scalar_t} * __restrict__ out_r,\n"
    "                 {scalar_t} * __restrict__ out_i,\n"
    "                 size_t n,\n"
    "                 const {scalar_t} * __restrict__ tw_r,\n"
    "                 const {scalar_t} * __restrict__ tw_i);"
)


def _scalar_t(dtype: str) -> str:
    return "float" if dtype == "f32" else "double"


def make_registry_header(configs: List[KernelConfig]) -> str:
    intl = [c for c in configs if c.layout == "interleaved"]
    splt = [c for c in configs if c.layout == "split"]

    def decl(c: KernelConfig) -> str:
        tmpl = DECL_TMPL_INTERLEAVED if c.layout == "interleaved" else DECL_TMPL_SPLIT
        return tmpl.format(func_name=c.func_name, scalar_t=_scalar_t(c.dtype))

    return REGISTRY_HEADER_TMPL.format(
        version=GENERATOR_VERSION,
        timestamp=_now(),
        interleaved_decls="\n".join(decl(c) for c in intl) or "/* none */",
        split_decls=      "\n".join(decl(c) for c in splt) or "/* none */",
    )


# ──────────────────────────────────────────────────────────────────────────────
# DAG → template context
# ──────────────────────────────────────────────────────────────────────────────

def build_template_context(cfg: KernelConfig) -> dict:
    """Return the Jinja2 template context dict for a given kernel config."""
    return {
        "func_name":         cfg.func_name,
        "radix":             cfg.radix,
        "dtype":             cfg.dtype,
        "vlen":              cfg.vlen,
        "lmul":              cfg.lmul,
        "layout":            cfg.layout,
        "sew":               cfg.sew,
        "vl_max":            cfg.vl_max,
        "timestamp":         _now(),
        "generator_version": GENERATOR_VERSION,
    }


# ──────────────────────────────────────────────────────────────────────────────
# DAG build dispatch
# ──────────────────────────────────────────────────────────────────────────────

def _build_dag(radix: int) -> Optional[DFT_DAG]:
    """Build and simplify the butterfly DAG for the given radix (group=0)."""
    builders = {
        2: lambda: build_radix2_butterfly(0, 2),
        4: lambda: build_radix4_butterfly(0, 4),
        8: lambda: build_radix8_butterfly(0, 8),
    }
    if radix not in builders:
        print(f"[generator] WARNING: No DAG builder for radix={radix}, skipping.")
        return None
    dag = builders[radix]()
    dag = simplify_dag(dag)
    return dag


# ──────────────────────────────────────────────────────────────────────────────
# Generation
# ──────────────────────────────────────────────────────────────────────────────

def _now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def generate_all(configs: List[KernelConfig],
                 outdir: Path,
                 registry_path: Optional[Path],
                 dry_run: bool) -> None:
    """
    Generate kernel source files and optionally the registry header.
    """
    # Set up Jinja2 environment
    if _JINJA2_OK:
        env = Environment(
            loader=FileSystemLoader(str(_HERE / "templates")),
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
        )
        tmpl = env.get_template("butterfly.c.j2")
    else:
        tmpl = None

    if not dry_run:
        outdir.mkdir(parents=True, exist_ok=True)

    generated: List[KernelConfig] = []

    for cfg in configs:
        if not cfg.is_valid():
            print(f"  [SKIP]  {cfg.func_name}  (register overflow: radix={cfg.radix}, "
                  f"lmul={cfg.lmul})")
            continue

        dag = _build_dag(cfg.radix)
        if dag is None:
            continue

        ctx = build_template_context(cfg)
        out_path = outdir / cfg.file_name

        if dry_run:
            print(f"  [DRY]   {out_path}")
        elif tmpl is not None:
            source = tmpl.render(**ctx)
            out_path.write_text(source)
            print(f"  [GEN]   {out_path}")
        else:
            print(f"  [SKIP]  {out_path}  (Jinja2 not available)")

        generated.append(cfg)

    # Write registry header
    if registry_path is not None:
        header = make_registry_header(generated)
        if dry_run:
            print(f"  [DRY]   {registry_path}  (registry header)")
        else:
            registry_path.parent.mkdir(parents=True, exist_ok=True)
            registry_path.write_text(header)
            print(f"  [GEN]   {registry_path}  (registry header)")

    print(f"\n[generator] Done: {len(generated)} kernel(s) generated.")


# ──────────────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="rvvfft butterfly kernel code generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--radix",   nargs="+", type=int,
                   default=[2, 4, 8],
                   metavar="R",
                   help="Radix values (default: 2 4 8)")
    p.add_argument("--dtype",   nargs="+",
                   default=["f32", "f64"],
                   choices=["f32", "f64"],
                   metavar="T",
                   help="Data types (default: f32 f64)")
    p.add_argument("--vlen",    nargs="+", type=int,
                   default=[256, 1024],
                   metavar="V",
                   help="Vector lengths (default: 256 1024)")
    p.add_argument("--lmul",    nargs="+", type=int,
                   default=None,
                   choices=[1, 2, 4, 8],
                   metavar="M",
                   help="LMUL values (default: auto-selected per config)")
    p.add_argument("--layout",  nargs="+",
                   default=["interleaved", "split"],
                   choices=["interleaved", "split"],
                   metavar="L",
                   help="Data layouts (default: both)")
    p.add_argument("--outdir",
                   default=str(_HERE.parent / "src" / "kernel" / "generated"),
                   metavar="DIR",
                   help="Output directory for generated .c files")
    p.add_argument("--registry",
                   default=None,
                   metavar="FILE",
                   help="Path for codelet_registry.h (default: <outdir>/codelet_registry.h)")
    p.add_argument("--verify",  action="store_true",
                   help="Run verify_math.py before generation")
    p.add_argument("--dry-run", action="store_true",
                   help="Print file names without writing")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    print(f"rvvfft codegen {GENERATOR_VERSION}")
    print(f"  radix  : {args.radix}")
    print(f"  dtype  : {args.dtype}")
    print(f"  vlen   : {args.vlen}")
    print(f"  lmul   : {args.lmul or 'auto'}")
    print(f"  layout : {args.layout}")
    print(f"  outdir : {args.outdir}")

    # Optional pre-flight mathematical verification
    if args.verify:
        print("\n[generator] Running mathematical verification …")
        import subprocess
        result = subprocess.run(
            [sys.executable, str(_HERE / "verify_math.py")],
            capture_output=False,
        )
        if result.returncode != 0:
            sys.exit("[generator] ABORT: Mathematical verification failed.")
        print()

    # Build configuration list
    configs: List[KernelConfig] = []
    for radix in args.radix:
        for dtype in args.dtype:
            sew = 32 if dtype == "f32" else 64
            for vlen in args.vlen:
                lmul_choices = args.lmul or [best_lmul(radix, vlen, sew)]
                for lmul in lmul_choices:
                    for layout in args.layout:
                        configs.append(KernelConfig(
                            radix=radix, dtype=dtype, vlen=vlen,
                            lmul=lmul, layout=layout,
                        ))

    print(f"\n[generator] {len(configs)} configurations to generate:\n")

    outdir = Path(args.outdir)
    registry_path = (
        Path(args.registry) if args.registry
        else outdir / "codelet_registry.h"
    )

    generate_all(configs, outdir, registry_path, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
